node {
    properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')), disableConcurrentBuilds(), pipelineTriggers([])])
    def dockerBin
    // Mark the code checkout 'stage'....

    stage('Preparation') {

        dockerBin = "/usr/bin/docker"

        echo "Git cloning the project"
        git branch: 'master',
        credentialsId: 'githubcredentials',
        url: 'https://github.com/zylklab/fractal.git'
        echo "Git Project successfully cloned"

        sh "git checkout develop-swarm"
    }

      stage('Release docker') {
          echo "release :: Inferrer"
          dir("/var/lib/jenkins/workspace/fractalmlserver/FractalMLServer-Lite/inferrer/flask_app") {
              docker.withRegistry('https://swarm.zylk.net/', 'swarmcredentials') {
                  sh "'${dockerBin}' image build -t deploy_inferrer:latest ."
                  sh "'${dockerBin}' image tag deploy_inferrer:latest swarm.zylk.net/fractalml/deploy_inferrer:latest"
                  sh "'${dockerBin}' push swarm.zylk.net/fractalml/deploy_inferrer:latest"
              }
          }
          echo "release :: Modelhost"
          dir("/var/lib/jenkins/workspace/fractalmlserver/FractalMLServer-Lite/modelhost/flask_app") {
              docker.withRegistry('https://swarm.zylk.net/', 'swarmcredentials') {
                  sh "'${dockerBin}' image build -t deploy_modelhost:latest ."
                  sh "'${dockerBin}' image tag deploy_modelhost:latest swarm.zylk.net/fractalml/deploy_modelhost:latest"
                  sh "'${dockerBin}' push swarm.zylk.net/fractalml/deploy_modelhost:latest"
              }
          }
          echo "release :: Prometheus"
          dir("/var/lib/jenkins/workspace/fractalmlserver/FractalMLServer-Lite/metrics/prometheus") {
              docker.withRegistry('https://swarm.zylk.net/', 'swarmcredentials') {
                  sh "'${dockerBin}' image build -t deploy_prometheus:latest ."
                  sh "'${dockerBin}' image tag deploy_prometheus:latest swarm.zylk.net/fractalml/deploy_prometheus:latest"
                  sh "'${dockerBin}' push swarm.zylk.net/fractalml/deploy_prometheus:latest"
              }
          }
          echo "release :: NGINX"
          dir("/var/lib/jenkins/workspace/fractalmlserver/FractalMLServer-Lite/inferrer/nginx") {
              docker.withRegistry('https://swarm.zylk.net/', 'swarmcredentials') {
                  sh "'${dockerBin}' image build -t deploy_nginx:latest ."
                  sh "'${dockerBin}' image tag deploy_nginx:latest swarm.zylk.net/fractalml/deploy_nginx:latest"
                  sh "'${dockerBin}' push swarm.zylk.net/fractalml/deploy_nginx:latest"
              }
          }
      }
    stage('Results') {
    }
}
